extends Node

signal intro_started
signal start_transition
signal check_win_lose_conditions

signal level_completed
signal goal_block_reached

signal set_display_text
signal update_music
signal set_active_camera

signal trigger_activation_changed

signal set_controls_lock
signal save_player_recording
signal bot_was_reset
signal bot_was_activated
signal bot_was_deactivated

signal pause
signal unpause
